apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
data:
  PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
spec:
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        version: v1
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: catalogue
          image: abdvswmdr/soqonicatalogue:40e75f2
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          command: ["/app"]
          args:
            - "-port=80"
            - "-DSN=$(DB_DSN)"
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: catalogue-secret
                  key: db-dsn
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: catalogue-kv
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
    - port: 80
      targetPort: 80
