apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soqoni-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "soqoni-route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - soqoni.tech
      secretName: soqoni-tls
  rules:
    - host: soqoni.tech
      http:
        paths:
          - path: /catalogue
            pathType: Prefix
            backend:
              service:
                name: catalogue
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8079
