apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: socksdb
  MYSQL_USER: catalogue_user
  MYSQL_PASSWORD: default_password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
spec:
  selector:
    matchLabels:
      app: catalogue-db
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: mysql
          # image: mysql:5.7
          # imagePullPolicy: IfNotPresent
          image: abdvswmdr/soqonicatalogue-db:3db5422
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
spec:
  selector:
    app: catalogue-db
  ports:
    - port: 3306
      targetPort: 3306
