apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalogue-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5737b2d8-f064-4ae7-8bbb-dfb7b99940da"
    keyvaultName: soqoni-kv
    tenantId: 3f639a9b-27c8-4403-82b1-ebfb88052d15
    objects: |
      array:
        - |
          objectName: catalogue-db-dsn
          objectType: secret
  secretObjects:
    - secretName: catalogue-secret
      type: Opaque
      data:
        - objectName: catalogue-db-dsn
          key: db-dsn
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: carts-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5737b2d8-f064-4ae7-8bbb-dfb7b99940da"
    keyvaultName: soqoni-kv
    tenantId: 3f639a9b-27c8-4403-82b1-ebfb88052d15
    objects: |
      array:
        - |
          objectName: carts-mongo-uri
          objectType: secret
  secretObjects:
    - secretName: carts-secret
      type: Opaque
      data:
        - objectName: carts-mongo-uri
          key: mongo-uri
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5737b2d8-f064-4ae7-8bbb-dfb7b99940da"
    keyvaultName: soqoni-kv
    tenantId: 3f639a9b-27c8-4403-82b1-ebfb88052d15
    objects: |
      array:
        - |
          objectName: auth-db-user
          objectType: secret
        - |
          objectName: auth-db-password
          objectType: secret
        - |
          objectName: auth-jwt-secret
          objectType: secret
        - |
          objectName: auth-admin-promote-secret
          objectType: secret
  secretObjects:
    - secretName: auth-secret
      type: Opaque
      data:
        - objectName: auth-db-user
          key: db-user
        - objectName: auth-db-password
          key: db-password
        - objectName: auth-jwt-secret
          key: jwt-secret
        - objectName: auth-admin-promote-secret
          key: admin-promote-secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5737b2d8-f064-4ae7-8bbb-dfb7b99940da"
    keyvaultName: soqoni-kv
    tenantId: 3f639a9b-27c8-4403-82b1-ebfb88052d15
    objects: |
      array:
        - |
          objectName: frontend-session-secret
          objectType: secret
  secretObjects:
    - secretName: frontend-secret
      type: Opaque
      data:
        - objectName: frontend-session-secret
          key: session-secret
